[INFO] Processing date: 2024-10-08
[2024-10-14 20:53:40] ./run_weekly_car_distillation_log_extension_single_rag2.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-08/2024-10-08_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-10-14 20:53:40
Traceback (most recent call last):
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'taskformer-model-13b-input'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/pipeline_periodic/get_extension_log_distillation.py", line 115, in get_distillation_data
    df = df[~df['taskformer-model-13b-input'].isna()]
             ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 'taskformer-model-13b-input'
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/transformers/configuration_utils.py:302: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Arguments: Namespace(api_url='http://172.24.139.210:16073/ligpt_with_api/search', embedding_model_path='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/bge-base-zh', is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', input_file='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-08/2024-10-08_rule_labeled.csv.gpt_labeled.csv', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation_car/')
Processing distillation data for date: 2024-10-08
Input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-08/2024-10-08_rule_labeled.csv.gpt_labeled.csv
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation_car/2024-10-08/extension/single_True_rag_True
Reading input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-08/2024-10-08_rule_labeled.csv.gpt_labeled.csv
Exception occurred while processing file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-08/2024-10-08_rule_labeled.csv.gpt_labeled.csv
raw log len: 5000
时效人设任务型query 数量： 0
Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/pipeline_periodic/get_extension_log_distillation.py", line 211, in <module>
    distillator.get_distillation_data(args.input_file)
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/pipeline_periodic/get_extension_log_distillation.py", line 136, in get_distillation_data
    unique_queries_with_metadata = DataFilter.get_unique_query(clean_queries_with_metadata, batch_size=64, BGE_MODEL_PATH=self.config['embedding_model_path'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/pipeline_periodic/data_processing.py", line 204, in get_unique_query
    embeddings = np.vstack(all_embeddings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/numpy/core/shape_base.py", line 289, in vstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: need at least one array to concatenate
[INFO] end_time: 2024-10-14 20:53:58 
[INFO] duration: 0 min 
[INFO] Processing date: 2024-10-09
[2024-10-14 20:53:58] ./run_weekly_car_distillation_log_extension_single_rag2.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-09/2024-10-09_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-10-14 20:53:58
Traceback (most recent call last):
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'taskformer-model-13b-input'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/pipeline_periodic/get_extension_log_distillation.py", line 115, in get_distillation_data
    df = df[~df['taskformer-model-13b-input'].isna()]
             ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 'taskformer-model-13b-input'
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/transformers/configuration_utils.py:302: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Arguments: Namespace(api_url='http://172.24.139.210:16073/ligpt_with_api/search', embedding_model_path='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/bge-base-zh', is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', input_file='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-09/2024-10-09_rule_labeled.csv.gpt_labeled.csv', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation_car/')
Processing distillation data for date: 2024-10-09
Input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-09/2024-10-09_rule_labeled.csv.gpt_labeled.csv
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation_car/2024-10-09/extension/single_True_rag_True
Reading input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-09/2024-10-09_rule_labeled.csv.gpt_labeled.csv
Exception occurred while processing file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-09/2024-10-09_rule_labeled.csv.gpt_labeled.csv
raw log len: 5000
时效人设任务型query 数量： 0
Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/pipeline_periodic/get_extension_log_distillation.py", line 211, in <module>
    distillator.get_distillation_data(args.input_file)
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/pipeline_periodic/get_extension_log_distillation.py", line 136, in get_distillation_data
    unique_queries_with_metadata = DataFilter.get_unique_query(clean_queries_with_metadata, batch_size=64, BGE_MODEL_PATH=self.config['embedding_model_path'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/pipeline_periodic/data_processing.py", line 204, in get_unique_query
    embeddings = np.vstack(all_embeddings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/numpy/core/shape_base.py", line 289, in vstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: need at least one array to concatenate
[INFO] end_time: 2024-10-14 20:54:13 
[INFO] duration: 0 min 
[INFO] Processing date: 2024-10-10
[2024-10-14 20:54:14] ./run_weekly_car_distillation_log_extension_single_rag2.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-10/2024-10-10_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-10-14 20:54:14
Traceback (most recent call last):
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'taskformer-model-13b-input'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/pipeline_periodic/get_extension_log_distillation.py", line 115, in get_distillation_data
    df = df[~df['taskformer-model-13b-input'].isna()]
             ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 'taskformer-model-13b-input'
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/transformers/configuration_utils.py:302: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Arguments: Namespace(api_url='http://172.24.139.210:16073/ligpt_with_api/search', embedding_model_path='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/bge-base-zh', is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', input_file='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-10/2024-10-10_rule_labeled.csv.gpt_labeled.csv', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation_car/')
Processing distillation data for date: 2024-10-10
Input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-10/2024-10-10_rule_labeled.csv.gpt_labeled.csv
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation_car/2024-10-10/extension/single_True_rag_True
Reading input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-10/2024-10-10_rule_labeled.csv.gpt_labeled.csv
Exception occurred while processing file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-10/2024-10-10_rule_labeled.csv.gpt_labeled.csv
raw log len: 5000
时效人设任务型query 数量： 0
Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/pipeline_periodic/get_extension_log_distillation.py", line 211, in <module>
    distillator.get_distillation_data(args.input_file)
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/pipeline_periodic/get_extension_log_distillation.py", line 136, in get_distillation_data
    unique_queries_with_metadata = DataFilter.get_unique_query(clean_queries_with_metadata, batch_size=64, BGE_MODEL_PATH=self.config['embedding_model_path'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/pipeline_periodic/data_processing.py", line 204, in get_unique_query
    embeddings = np.vstack(all_embeddings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/numpy/core/shape_base.py", line 289, in vstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: need at least one array to concatenate
[INFO] end_time: 2024-10-14 20:54:29 
[INFO] duration: 0 min 
[INFO] Processing date: 2024-10-11
[2024-10-14 20:54:29] ./run_weekly_car_distillation_log_extension_single_rag2.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-11/2024-10-11_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-10-14 20:54:29
Traceback (most recent call last):
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'taskformer-model-13b-input'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/pipeline_periodic/get_extension_log_distillation.py", line 115, in get_distillation_data
    df = df[~df['taskformer-model-13b-input'].isna()]
             ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 'taskformer-model-13b-input'
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/transformers/configuration_utils.py:302: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Arguments: Namespace(api_url='http://172.24.139.210:16073/ligpt_with_api/search', embedding_model_path='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/bge-base-zh', is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', input_file='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-11/2024-10-11_rule_labeled.csv.gpt_labeled.csv', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation_car/')
Processing distillation data for date: 2024-10-11
Input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-11/2024-10-11_rule_labeled.csv.gpt_labeled.csv
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation_car/2024-10-11/extension/single_True_rag_True
Reading input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-11/2024-10-11_rule_labeled.csv.gpt_labeled.csv
Exception occurred while processing file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-10-11/2024-10-11_rule_labeled.csv.gpt_labeled.csv
raw log len: 5000
时效人设任务型query 数量： 0
Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/pipeline_periodic/get_extension_log_distillation.py", line 211, in <module>
    distillator.get_distillation_data(args.input_file)
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/pipeline_periodic/get_extension_log_distillation.py", line 136, in get_distillation_data
    unique_queries_with_metadata = DataFilter.get_unique_query(clean_queries_with_metadata, batch_size=64, BGE_MODEL_PATH=self.config['embedding_model_path'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/pipeline_periodic/data_processing.py", line 204, in get_unique_query
    embeddings = np.vstack(all_embeddings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/numpy/core/shape_base.py", line 289, in vstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: need at least one array to concatenate
[INFO] end_time: 2024-10-14 20:54:45 
[INFO] duration: 0 min 
