nohup: ignoring input
[INFO] Processing date: 2024-08-23
[2024-08-30 09:51:14] ./run_weekly_car_distillation_log_raw_single_rag2.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-08-23/2024-08-23_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-08-30 09:51:14
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /opt/conda/envs/rhm_env did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('Asia/Shanghai')}
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/transformers/configuration_utils.py:364: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/get_raw_log_distillation.py", line 49, in get_distillation_data
    unique_queries_with_metadata = DataFilter.get_unique_query(query_ls, batch_size=64, BGE_MODEL_PATH=self.config['embedding_model_path'])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/data_processing.py", line 177, in get_unique_query
    embeddings = np.vstack(all_embeddings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/numpy/core/shape_base.py", line 289, in vstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: need at least one array to concatenate

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so...
Arguments: Namespace(is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', input_file='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-08-23/2024-08-23_rule_labeled.csv.gpt_labeled.csv', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation_car/', embedding_model_path='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/bge-base-zh')
Processing distillation data for date: 2024-08-23
Input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-08-23/2024-08-23_rule_labeled.csv.gpt_labeled.csv
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation_car/2024-08-23/raw/single_True_rag_True
Exception occurred while processing file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-08-23/2024-08-23_rule_labeled.csv.gpt_labeled.csv
Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/get_raw_log_distillation.py", line 104, in <module>
    distillator.get_distillation_data(args.input_file)
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/get_raw_log_distillation.py", line 62, in get_distillation_data
    self.check_and_generate_gpt4_files(outfolder, prompt_path)
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/base_distillation.py", line 77, in check_and_generate_gpt4_files
    if not missing_files and (wrong_data_count / total_data_count) <= 0.5:
                              ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
[INFO] end_time: 2024-08-30 09:51:31
[INFO] duration: 0 min 
[INFO] Processing date: 2024-08-24
[2024-08-30 09:51:31] ./run_weekly_car_distillation_log_raw_single_rag2.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-08-24/2024-08-24_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-08-30 09:51:31
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /opt/conda/envs/rhm_env did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('Asia/Shanghai')}
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/transformers/configuration_utils.py:364: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/get_raw_log_distillation.py", line 49, in get_distillation_data
    unique_queries_with_metadata = DataFilter.get_unique_query(query_ls, batch_size=64, BGE_MODEL_PATH=self.config['embedding_model_path'])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/data_processing.py", line 177, in get_unique_query
    embeddings = np.vstack(all_embeddings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/rhm_env/lib/python3.11/site-packages/numpy/core/shape_base.py", line 289, in vstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: need at least one array to concatenate

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so...
Arguments: Namespace(is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', input_file='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-08-24/2024-08-24_rule_labeled.csv.gpt_labeled.csv', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation_car/', embedding_model_path='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/bge-base-zh')
Processing distillation data for date: 2024-08-24
Input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-08-24/2024-08-24_rule_labeled.csv.gpt_labeled.csv
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation_car/2024-08-24/raw/single_True_rag_True
Exception occurred while processing file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-08-24/2024-08-24_rule_labeled.csv.gpt_labeled.csv
Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/get_raw_log_distillation.py", line 104, in <module>
    distillator.get_distillation_data(args.input_file)
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/get_raw_log_distillation.py", line 62, in get_distillation_data
    self.check_and_generate_gpt4_files(outfolder, prompt_path)
  File "/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/src/weekly_run/base_distillation.py", line 77, in check_and_generate_gpt4_files
    if not missing_files and (wrong_data_count / total_data_count) <= 0.5:
                              ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
[INFO] end_time: 2024-08-30 09:51:47
[INFO] duration: 0 min 
[INFO] Processing date: 2024-08-25
[2024-08-30 09:51:47] ./run_weekly_car_distillation_log_raw_single_rag2.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-08-25/2024-08-25_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-08-30 09:51:47
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /opt/conda/envs/rhm_env did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('Asia/Shanghai')}
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/transformers/configuration_utils.py:364: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so...
Arguments: Namespace(is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', input_file='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-08-25/2024-08-25_rule_labeled.csv.gpt_labeled.csv', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation_car/', embedding_model_path='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/bge-base-zh')
Processing distillation data for date: 2024-08-25
Input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-08-25/2024-08-25_rule_labeled.csv.gpt_labeled.csv
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation_car/2024-08-25/raw/single_True_rag_True
Saved chunk 1 to /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation_car/2024-08-25/raw/single_True_rag_True/split_data/chunk_1.csv
Regenerating missing GPT-4 file for split data file: chunk_1.csv
Reading oneshot prompt from: /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt
Reading oneshot prompt done.
Building prompts for dataframe entries.
Calling GPT-4 API
剩余case 100 / 100
  0%|          | 0/100 [00:00<?, ?it/s]  1%|          | 1/100 [00:09<15:18,  9.28s/it]  2%|▏         | 2/100 [00:13<10:09,  6.22s/it]  5%|▌         | 5/100 [00:19<05:09,  3.25s/it]  8%|▊         | 8/100 [00:25<03:58,  2.59s/it]  9%|▉         | 9/100 [00:27<03:55,  2.59s/it] 11%|█         | 11/100 [00:31<03:21,  2.27s/it] 12%|█▏        | 12/100 [00:31<02:44,  1.86s/it] 13%|█▎        | 13/100 [00:34<02:53,  2.00s/it] 14%|█▍        | 14/100 [00:36<03:03,  2.14s/it] 15%|█▌        | 15/100 [00:40<03:32,  2.50s/it] 17%|█▋        | 17/100 [00:42<02:40,  1.93s/it] 18%|█▊        | 18/100 [00:46<03:25,  2.51s/it] 19%|█▉        | 19/100 [00:52<04:33,  3.38s/it] 21%|██        | 21/100 [01:02<05:15,  3.99s/it] 22%|██▏       | 22/100 [01:06<05:03,  3.90s/it] 26%|██▌       | 26/100 [01:08<02:32,  2.06s/it] 27%|██▋       | 27/100 [01:10<02:29,  2.05s/it] 28%|██▊       | 28/100 [01:18<03:39,  3.05s/it] 31%|███       | 31/100 [01:19<02:14,  1.95s/it] 32%|███▏      | 32/100 [01:20<01:51,  1.64s/it] 34%|███▍      | 34/100 [01:26<02:17,  2.08s/it] 36%|███▌      | 36/100 [01:30<02:18,  2.17s/it] 39%|███▉      | 39/100 [01:32<01:32,  1.52s/it] 40%|████      | 40/100 [01:36<01:51,  1.86s/it] 42%|████▏     | 42/100 [01:42<02:10,  2.26s/it] 44%|████▍     | 44/100 [01:51<02:49,  3.03s/it] 46%|████▌     | 46/100 [01:52<01:57,  2.18s/it] 47%|████▋     | 47/100 [02:03<03:22,  3.82s/it] 52%|█████▏    | 52/100 [02:19<02:45,  3.44s/it] 59%|█████▉    | 59/100 [02:26<01:29,  2.18s/it] 61%|██████    | 61/100 [02:26<01:10,  1.81s/it] 64%|██████▍   | 64/100 [02:35<01:16,  2.12s/it] 65%|██████▌   | 65/100 [02:38<01:16,  2.20s/it] 67%|██████▋   | 67/100 [02:39<00:56,  1.71s/it] 68%|██████▊   | 68/100 [02:46<01:22,  2.58s/it] 71%|███████   | 71/100 [02:59<01:33,  3.21s/it] 75%|███████▌  | 75/100 [03:04<01:01,  2.44s/it] 76%|███████▌  | 76/100 [03:06<00:56,  2.37s/it] 78%|███████▊  | 78/100 [03:08<00:44,  2.01s/it] 79%|███████▉  | 79/100 [03:09<00:36,  1.73s/it] 81%|████████  | 81/100 [03:18<00:50,  2.67s/it] 82%|████████▏ | 82/100 [03:23<00:56,  3.12s/it] 84%|████████▍ | 84/100 [03:29<00:48,  3.02s/it] 87%|████████▋ | 87/100 [03:31<00:27,  2.11s/it] 88%|████████▊ | 88/100 [03:36<00:30,  2.53s/it] 90%|█████████ | 90/100 [03:40<00:23,  2.31s/it] 91%|█████████ | 91/100 [03:44<00:24,  2.72s/it] 94%|█████████▍| 94/100 [03:51<00:15,  2.53s/it] 95%|█████████▌| 95/100 [03:55<00:13,  2.77s/it]100%|██████████| 100/100 [03:56<00:00,  1.30s/it]100%|██████████| 100/100 [03:56<00:00,  2.36s/it]
Parsing GPT-4 response
All GPT-4 files are generated and valid. Total files: 1
[INFO] end_time: 2024-08-30 09:58:05
[INFO] duration: 6 min 
[INFO] Processing date: 2024-08-26
[2024-08-30 09:58:05] ./run_weekly_car_distillation_log_raw_single_rag2.sh:56  /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-08-26/2024-08-26_rule_labeled.csv.gpt_labeled.csv is ready.
[INFO] begin_time: 2024-08-30 09:58:05
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /opt/conda/envs/rhm_env did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('Asia/Shanghai')}
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/transformers/configuration_utils.py:364: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
/opt/conda/envs/rhm_env/lib/python3.11/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /opt/conda/envs/rhm_env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so...
Arguments: Namespace(is_single_flag=True, is_rag_flag=True, model_url='https://rhm-gpt4.fc.chj.cloud/gpt4o/conversation', model_name='gpt4o', prompt_path='/mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt', input_file='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-08-26/2024-08-26_rule_labeled.csv.gpt_labeled.csv', base_output_path='/mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation_car/', embedding_model_path='/mnt/pfs-guan-ssai/nlu/wangxiaoyuan/bge-base-zh')
Processing distillation data for date: 2024-08-26
Input file: /mnt/pfs-guan-ssai/nlu/wangxiaoyuan/online-data-car/2024-08-26/2024-08-26_rule_labeled.csv.gpt_labeled.csv
Output folder: /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation_car/2024-08-26/raw/single_True_rag_True
Saved chunk 1 to /mnt/pfs-guan-ssai/nlu/renhuimin/data/log_distillation_car/2024-08-26/raw/single_True_rag_True/split_data/chunk_1.csv
Regenerating missing GPT-4 file for split data file: chunk_1.csv
Reading oneshot prompt from: /mnt/pfs-guan-ssai/nlu/renhuimin/rag_tool/conf/generation_prompts/generation_单轮RAG日志蒸馏.txt
Reading oneshot prompt done.
Building prompts for dataframe entries.
Calling GPT-4 API
剩余case 100 / 100
  0%|          | 0/100 [00:00<?, ?it/s]  1%|          | 1/100 [00:09<15:41,  9.51s/it]  2%|▏         | 2/100 [00:10<07:07,  4.36s/it]  4%|▍         | 4/100 [00:17<06:25,  4.01s/it]  5%|▌         | 5/100 [00:26<08:49,  5.57s/it]  8%|▊         | 8/100 [00:29<04:18,  2.81s/it]  9%|▉         | 9/100 [00:34<05:10,  3.41s/it] 11%|█         | 11/100 [00:37<03:52,  2.61s/it] 12%|█▏        | 12/100 [00:56<09:06,  6.21s/it] 16%|█▌        | 16/100 [00:57<04:01,  2.87s/it] 17%|█▋        | 17/100 [01:05<05:05,  3.68s/it] 20%|██        | 20/100 [01:16<05:01,  3.77s/it] 23%|██▎       | 23/100 [01:21<03:47,  2.96s/it] 26%|██▌       | 26/100 [01:28<03:25,  2.78s/it] 29%|██▉       | 29/100 [01:32<02:43,  2.30s/it] 30%|███       | 30/100 [01:42<03:53,  3.34s/it] 31%|███       | 31/100 [01:45<03:39,  3.18s/it] 33%|███▎      | 33/100 [02:02<05:29,  4.92s/it] 38%|███▊      | 38/100 [02:08<03:03,  2.97s/it] 39%|███▉      | 39/100 [02:09<02:41,  2.65s/it] 40%|████      | 40/100 [02:13<02:51,  2.86s/it] 41%|████      | 41/100 [02:16<02:49,  2.86s/it] 42%|████▏     | 42/100 [02:32<05:23,  5.58s/it] 43%|████▎     | 43/100 [02:32<04:12,  4.43s/it] 44%|████▍     | 44/100 [02:33<03:21,  3.59s/it] 46%|████▌     | 46/100 [02:37<02:39,  2.95s/it] 47%|████▋     | 47/100 [02:37<02:02,  2.31s/it] 48%|████▊     | 48/100 [04:29<25:12, 29.09s/it] 74%|███████▍  | 74/100 [04:32<01:17,  2.98s/it] 77%|███████▋  | 77/100 [04:42<01:10,  3.05s/it] 80%|████████  | 80/100 [04:44<00:53,  2.65s/it] 81%|████████  | 81/100 [04:50<00:55,  2.92s/it] 84%|████████▍ | 84/100 [05:04<00:53,  3.33s/it] 89%|████████▉ | 89/100 [05:07<00:25,  2.32s/it] 90%|█████████ | 90/100 [05:08<00:21,  2.19s/it] 92%|█████████▏| 92/100 [05:20<00:24,  3.02s/it] 93%|█████████▎| 93/100 [05:25<00:23,  3.32s/it] 97%|█████████▋| 97/100 [05:26<00:05,  1.96s/it] 98%|█████████▊| 98/100 [05:32<00:04,  2.44s/it] 99%|█████████▉| 99/100 [05:36<00:02,  2.71s/it]100%|██████████| 100/100 [05:36<00:00,  3.36s/it]
chatgpt api 调用异常：Expecting value: line 1 column 1 (char 0)
chatgpt api 调用异常：('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
chatgpt api 调用异常：HTTPSConnectionPool(host='rhm-gpt4.fc.chj.cloud', port=443): Max retries exceeded with url: /gpt4o/conversation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f75ec0de590>: Failed to establish a new connection: [Errno 104] Connection reset by peer'))
chatgpt api 调用异常：('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
chatgpt api 调用异常：('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Parsing GPT-4 response
All GPT-4 files are generated and valid. Total files: 1
[INFO] end_time: 2024-08-30 10:09:29
[INFO] duration: 11 min 
